import Navbar from './Navbar'
import Footer from './Footer'

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col" style={{ background: 'var(--bg-base)', color: 'var(--text-muted)' }}>
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>Terms of Service</h1>
        <p className="text-sm mb-12">Effective date: March 25, 2025</p>

        <Section title="1. Acceptance">
          <p>By creating an account or using Brew AI, you agree to these Terms. If you do not agree, do not use the service.</p>
        </Section>

        <Section title="2. What Brew AI Does">
          <p>Brew AI is an AI-powered resume tailoring tool. You upload a base resume, paste a job description, and we generate a tailored version optimized for that role. Output is generated by AI and is provided as-is — we do not guarantee that any resume will result in an interview or job offer.</p>
        </Section>

        <Section title="3. Your Account">
          <ul>
            <li>You must be at least 13 years old to use Brew AI.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You may not share your account with others or use it for commercial reselling of our output without written permission.</li>
          </ul>
        </Section>

        <Section title="4. Your Content">
          <ul>
            <li>You retain full ownership of your resume content and any job descriptions you submit.</li>
            <li>By using Brew AI, you grant us a limited license to process your content solely for the purpose of providing the service.</li>
            <li>You are responsible for ensuring you have the right to submit any content you upload (e.g., do not submit others' resumes without permission).</li>
            <li>Do not submit content that is illegal, defamatory, or violates third-party rights.</li>
          </ul>
        </Section>

        <Section title="5. AI Output">
          <p>Tailored resumes are generated by AI. We do not guarantee accuracy, completeness, or fitness for any particular job. Always review AI-generated content before submitting it to an employer. You are solely responsible for the resumes you send.</p>
        </Section>

        <Section title="6. Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>Attempt to reverse-engineer, scrape, or abuse the Brew AI API or infrastructure.</li>
            <li>Use the service to generate fraudulent, misleading, or deceptive resumes.</li>
            <li>Interfere with or disrupt the service or other users.</li>
          </ul>
        </Section>

        <Section title="7. Termination">
          <p>We may suspend or terminate your account at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time by using the <strong>Contact</strong> button in the footer.</p>
        </Section>

        <Section title="8. Disclaimers">
          <p>Brew AI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including lost job opportunities.</p>
        </Section>

        <Section title="9. Changes to These Terms">
          <p>We may update these Terms as the product evolves. Continued use after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="10. Contact">
          <p>Questions? Use the <strong>Contact</strong> button in the footer to reach us.</p>
        </Section>
      </main>
      <Footer />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>{title}</h2>
      <div className="prose-list space-y-3 text-sm leading-relaxed" style={{ '--tw-prose-strong': 'var(--text-primary)' } as React.CSSProperties}>
        {children}
      </div>
    </section>
  )
}
